# Generated by Django 3.0.4 on 2021-06-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irst_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('class_name', models.CharField(max_length=30)),
                ('roll_no', models.CharField(max_length=30)),
            ],
        ),
    ]
