# Generated by Django 3.0.4 on 2021-06-26 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='irst_name',
            new_name='first_name',
        ),
    ]
